using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AILZ80CPU
{
    public enum TimingCycleEnum
    {
        None,
        M1_T1_H,
        M1_T1_L,
        M1_T2_H,
        M1_T2_L,
        M1_T3_H,
        M1_T3_L,
        M1_T4_H,
        M1_T4_L,
        M2_T1_H,
        M2_T1_L,
        M2_T2_H,
        M2_T2_L,
        M2_T3_H,
        M2_T3_L,
        M2_T4_H,
        M2_T4_L,
        M3_T1_H,
        M3_T1_L,
        M3_T2_H,
        M3_T2_L,
        M3_T3_H,
        M3_T3_L,
        R1_T1_H,
        R1_T1_L,
        R1_T2_H,
        R1_T2_L,
        R1_T3_H,
        R1_T3_L,
        R2_T1_H,
        R2_T1_L,
        R2_T2_H,
        R2_T2_L,
        R2_T3_H,
        R2_T3_L,
        R2_T4_H,
        R2_T4_L,
        W1_T1_H,
        W1_T1_L,
        W1_T2_H,
        W1_T2_L,
        W1_T3_H,
        W1_T3_L,
        W2_T1_H,
        W2_T1_L,
        W2_T2_H,
        W2_T2_L,
        W2_T3_H,
        W2_T3_L,
        IR_T1_H,
        IR_T1_L,
        IR_T2_H,
        IR_T2_L,
        IR_T3_H,
        IR_T3_L,
        IW_T1_H,
        IW_T1_L,
        IW_T2_H,
        IW_T2_L,
        IW_T3_H,
        IW_T3_L,
    }
}
